stages: [deploy]

deploy_dev:
  stage: deploy
  tags: [web-senior-dev]
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'

  variables:
    DEPLOY_DIR: "/opt/web-senior"
    NVM_DIR: "/home/gitlab-runner/.nvm"

  script:
    - . "$NVM_DIR/nvm.sh"
    - nvm use 20

    - node -v
    - npm -v
    - pm2 -v

    - echo "== install & build =="
    - npm install
    - npm run build

    - echo "== deploy =="
    - mkdir -p "$DEPLOY_DIR"
    - rsync -a --delete build/ "$DEPLOY_DIR/"

  after_script:
    - ls -al "$DEPLOY_DIR" | head -n 30 || true